language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

notifications:
  email:
    - recipients:
      - andrew.e.kimberly@gmail.com

install:
  - npm install
  - npm run build

script:
  - npm run ci
